- source/donation/index.rst
> ISSHA-324 add donor list to donation page

- source/committee/index.rst
- source/committee/license.rst
- チケット: https://pyconjp.atlassian.net/browse/ISSHA-309
レビューしてほしいこと
- https://pyconjp.atlassian.net/browse/ISSHA-279 終了後にマージする(写真のライセンス適用がまだなので)
> ISSHA-309 ライセンスについてのページを追加

- source/index.rst
> 2017の価格が誤って記載されているので、予定と入れた

- source/annualreport/index.rst
https://pyconjp.atlassian.net/browse/ISSHA-1040 
承認後に公開
> ISSHA-1040 2017年度決算報告

- source/index.rst
> add 2019 official page

- source/sponsor/index.rst
- source/sponsor/sponsor.rst
スポンサーページに2019のスポンサー向け情報へのリンク追加
> ISSHA-1680 add 2019 sponsor info

- source/index.rst
www.pycon.jp TOPに2019問い合わせ先を追加するPR
> 2019 contact

- source/index.rst
blogのpyconjp2020 ラベルの最古あたりに問い合わせ先置いておくこと。
PyCon JP 2020 の情報を最低限だけTOPに記載
> NEZ-29 add PyCon JP 2020 information

- source/index.rst
PyCon JP 2019のタスクが終了したので、TOPページから外す。
> WYI-389-end-2019

- source/index.rst
> fix PyCon JP 2020 to online

- source/index.rst
PyCon JP 2021情報の掲載、Twitterアカウントの変更
> PyCon JP 2021情報の掲載、Twitterアカウントの変更

- source/committee/board_history.rst
- source/committee/index.rst
> ISSHA-2385 理事の履歴ページを追加

- source/support/bootcamp.rst
内容に間違いがないか、掲載する場所が適切であるか、レビューをお願いします。
> ISSHA-2228 「Python Boot Campのその後」記事URLのまとめを追加

- source/index.rst
- source/organizer/index.rst
- ISSHA-2484 Add result of PyCon JP 2021
- Correct typo for PyCon JP 2020
- ISSHA-2484 Update plan for 2022
> ISSHA-2484 Add result for 2021 and update plan for 2022

- source/index.rst
PyCon JP 2022 の開催日と公式ウェブサイトを掲載しました。
> PyCon JP 2022 の開催日と公式ウェブサイトの掲載

- source/support/bootcamp.rst
* https://pyconjp.atlassian.net/browse/ISSHA-2731
* 貢献者一覧を追加した
> ISSHA-2731 add pycampp contributors

- source/committee/board.rst
- source/committee/board_history.rst
* https://pyconjp.atlassian.net/browse/ISSHA-2770
> ISSHA-2770 理事を更新

- source/support/community.rst
> ISSHA-2948 Add DjangoCongress JP 2023

- source/index.rst
* トップページを更新
* このBlogへのリンクを追加 https://pyconjp.blogspot.com/2023/11/pyconapac2023-statement.html
> ISSHA-3066 update pycon apac 2023

- source/committee/board.md
- source/committee/english.md
英語プロフィール追加
* preview
* https://wwwpyconjp--98.org.readthedocs.build/committee/board.html#maaya-ishida
* https://wwwpyconjp--98.org.readthedocs.build/committee/english.html#maaya-ishida
> プロフィールの追加・編集

- source/organizer/index.md
> イベント主催事業に2024を追加

- source/support/goods.md
> Add annotation to entrance banner

- source/policies/internet-policy.md
bit.ly を使用した回避策
以下の問題により「&」を含むリンク URL を作成できないため
https://github.com/executablebooks/MyST-Parser/issues/760
> Add English translation of Internet connection service provision policy

- source/support/community.md
https://pyconjp.atlassian.net/browse/ISSHA-3506
ビルド結果
https://wwwpyconjp--114.org.readthedocs.build/support/community.html
> コミュニティ支援ページにSciPyData2025を掲載

- source/support/community.md
> ISSHA-3544 Add DjangoCongress JP 2025 (Online)

- source/committee/members.md
* https://pyconjp.atlassian.net/browse/ISSHA-3715
* Preview: https://wwwpyconjp--120.org.readthedocs.build/committee/members.html
> ISSHA-3715 add operating member category
